
# {{{ health checkers
### profiles - users - auth
GET http://localhost:8001/health

GET http://localhost:8002/health

GET http://localhost:8003/health

### fmc
GET http://localhost:8005/health

### questions - answers
GET http://localhost:8011/health

GET http://localhost:8012/health

### slides - forms - externals
GET http://localhost:8021/health

GET http://localhost:8022/health

GET http://localhost:8023/health

### resources - papers
GET http://localhost:8031/health

GET http://localhost:8032/health

### local
GET http://localhost:8000/health
# }}}

### auth bypass
GET http://localhost:8003/auth/bypass/1
Accept: application/json

# {{{ resources

GET http://localhost:8000/api/v1/resource
Accept: application/json
Authorization: Bearer 

GET http://localhost:8000/api/v1/resource/4
Accept: application/json
Authorization: Bearer 

POST http://localhost:8000/api/v1/resource
Accept: application/json
Authorization: Bearer 
Content-Type: application/json

{
  "resource_type": "slides",
  "title": "Título 5",
  "description": ""
}

PUT http://localhost:8000/api/v1/resource/5
Accept: application/json
Authorization: Bearer 
Content-Type: application/json

{
  "resource_type": "module",
  "title": "Título 5",
  "description": "Descripción para el título 5"
}

### Pendiente ->

POST http://localhost:8000/api/v1/resource
Accept: application/json
Authorization: Bearer 
Content-Type: application/json

{
  "resource_type": "form",
  "title": "Título 4",
  "description": "",
  "content": {
    "form": "hola caracola"
  }
}

POST http://localhost:8000/api/v1/resource
Accept: application/json
Authorization: Bearer 
Content-Type: application/json

{
  "resource_type": "slides",
  "title": "Título 4",
  "description": "",
  "content": {
    "slides": [
      {
        "slide_type": "content",
        "content": "",
        "title": "Título 9"
      },
      {
        "slide_type": "content",
        "content": "Content del título 5",
        "title": "Título 10"
      }
    ]
  }
}

PUT http://localhost:8000/api/v1/resource/4
Accept: application/json
Authorization: Bearer 
Content-Type: application/json

{
  "resource_type": "slides",
  "title": "Título 4",
  "description": "",
  "content": {
    "slides": [
      {
        "id": 9,
        "slide_type": "content",
        "content": "Content del título 9",
        "title": "Título 9"
      },
      {
        "id": 10,
        "slide_type": "content",
        "content": "Content del título 10",
        "title": "Título 10"
      }
    ]
  }
}

# }}}
